apiVersion: v1
kind: ServiceAccount
metadata:
  name: doomguy
  namespace: {{ .Values.namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monster-deployment
  namespace: {{ .Values.namespace }}-monsters

---
{{- if eq .Values.namespace "dennisvandenboom" }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monster-control
rules:
  - verbs:
      - get
      - list
      - watch
      - kill
    apiGroups:
      - ''
    resources:
      - pods
{{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.namespace }}-monster-control
subjects:
  - kind: ServiceAccount
    name: doomguy
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monster-control

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.namespace }}-system:image-puller
  namespace: doom-images
subjects:
  - kind: ServiceAccount
    name: doomguy
    namespace: {{ .Values.namespace }}
  - kind: ServiceAccount
    name: monster-deployment
    namespace: {{ .Values.namespace }}-monsters
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'